"""create tables

Revision ID: e07a2e7c6e6e
Revises: 
Create Date: 2023-10-27 18:35:59.538023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e07a2e7c6e6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('patient_id', table_name='demographics')
    op.drop_table('demographics')
    op.drop_index('MRN', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MRN', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('patient_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('MRN', 'patients', ['MRN'], unique=False)
    op.create_table('demographics',
    sa.Column('demographic_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], name='demographics_ibfk_1'),
    sa.PrimaryKeyConstraint('demographic_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('patient_id', 'demographics', ['patient_id'], unique=False)
    # ### end Alembic commands ###
